version: '3.8'

services:
  tradingbot-api:
    build:
      context: .
      dockerfile: TradingBot.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    depends_on:
      - signal-engine
    networks:
      - tradingbot-network
    volumes:
      - ./TradingBot.Api/appsettings.Development.json:/app/appsettings.Development.json:ro

  signal-engine:
    build:
      context: .
      dockerfile: TradingBot.SignalEngine/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    networks:
      - tradingbot-network
    healthcheck:
      test: ["CMD", "python", "health.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  tradingbot-network:
    driver: bridge

volumes:
  tradingbot-data:
